C#crudweb/Models/ContactoModelo.cs
using System.ComponentModel.DataAnnotations;
namespace C_crudweb.Models
{
    public class ContactoModelo
    {
        
        public int IdContacto { get; set; }
        [Required(ErrorMessage ="El campo Nombre es obligatorio")]
        public string? Nombre { get; set; }
        [Required(ErrorMessage = "El campo Teléfono es obligatorio")]
        public string? Telefono { get; set; }
        [Required(ErrorMessage = "El campo Correo es obligatorio")]
        public string? Correo { get; set; }
    }
}

C#crudweb/Models/ErrorViewModel.cs
namespace C_crudweb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

C#crudweb/Controllers/HomeController.cs
using C_crudweb.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace C_crudweb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

C#crudweb/Controllers/MantenedorController.cs
using Microsoft.AspNetCore.Mvc;
using C_crudweb.Datos;
using C_crudweb.Models;


namespace C_crudweb.Controllers
{
    public class MantenedorController : Controller
    {
        ContactoDatos contactoDatos=new ContactoDatos();
        public IActionResult Listar()
        {
            var objLista = contactoDatos.Listar();
            return View(objLista);
        } 
        public IActionResult GuardarLista()
        {
            return View();
        }          
        public IActionResult Guardar(ContactoModelo objContacto)
        {
            if (!ModelState.IsValid) return View();

            var respuesta = contactoDatos.GuardarContacto(objContacto);
            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }

        public IActionResult Editar(int IdContacto)
        {
            var objContacto = contactoDatos.ListarContacto(IdContacto);
            return View(objContacto);
        }        
        
        [HttpPost]
        public IActionResult Modificar(ContactoModelo objContacto)
        {
            if (!ModelState.IsValid) return View();

            var respuesta = contactoDatos.EditarContacto(objContacto);

            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }

        public IActionResult Eliminar(int IdContacto)
        {
            var objContacto = contactoDatos.ListarContacto(IdContacto);
            return View(objContacto);
        }

        [HttpPost]
        public IActionResult Eliminar(ContactoModelo objContacto)
        {
            var respuesta = contactoDatos.BorrarContacto(objContacto.IdContacto);

            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }
    }
}

C#crudweb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

C#crudweb/Views/Mantenedor/Editar.cshtml
@model ContactoModelo;
@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Modificar Contacto
    </div>
    <div class="card-body">
        <form asp-action="Modificar" asp-controller="Mantenedor" method="post">
            <input asp-for="IdContacto" type="hidden" class="form-control" id="idcontacto" aria-describedby="NameHelp">
            <div class="mb-3">
                <label for="nombre" class="form-label">Nombre:</label>
                <input asp-for="Nombre" type="text" class="form-control" id="nombre" aria-describedby="NameHelp">
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label for="telefono" class="form-label">Teléfono:</label>
                <input asp-for="Telefono" type="text" class="form-control" id="telefono">
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label for="mail" class="form-label">Correo:</label>
                <input asp-for="Correo" type="email" class="form-control" id="mail">
                <span asp-validation-for="Correo" class="text-danger"></span>
            </div>

            <button type="submit" class="btn btn-primary">Guardar</button>
            <a asp-action="Listar" asp-controller="Mantenedor" class="btn btn-warning">Volver a la lista</a>
        </form>
    </div>
</div>

C#crudweb/Views/Mantenedor/Eliminar.cshtml
@model ContactoModelo;
@{
    ViewData["Title"] = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Eliminar Contacto
    </div>
    <div class="card-body">
        <form asp-action="Eliminar" asp-controller="Mantenedor" method="post">
            <input asp-for="IdContacto" type="hidden" class="form-control" id="idcontacto" aria-describedby="NameHelp">
            <div class="mb-3">
                <label for="nombre" class="form-label">Nombre:</label>
                <input asp-for="Nombre" type="text" class="form-control" id="nombre" aria-describedby="NameHelp">
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label for="telefono" class="form-label">Teléfono:</label>
                <input asp-for="Telefono" type="text" class="form-control" id="telefono">
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label for="mail" class="form-label">Correo:</label>
                <input asp-for="Correo" type="email" class="form-control" id="mail">
                <span asp-validation-for="Correo" class="text-danger"></span>
            </div>

            <button type="submit" class="btn btn-danger">Eliminar</button>
            <a asp-action="Listar" asp-controller="Mantenedor" class="btn btn-warning">Volver a la lista</a>
        </form>
    </div>
</div>

C#crudweb/Views/Mantenedor/Guardar.cshtml
@model ContactoModelo;
@{
    ViewData["Title"] = "Guardar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Crear Contacto
    </div>
    <div class="card-body">
        <form asp-action="Guardar" asp-controller="Mantenedor" method="post">
            <div class="mb-3">
                <label for="nombre" class="form-label">Nombre:</label>
                <input asp-for="Nombre" type="text" class="form-control" id="nombre" aria-describedby="NameHelp">
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label for="telefono" class="form-label">Teléfono:</label>
                <input asp-for="Telefono" type="text" class="form-control" id="telefono">
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label for="mail" class="form-label">Correo:</label>
                <input asp-for="Correo" type="email" class="form-control" id="mail">
                <span asp-validation-for="Correo" class="text-danger"></span>
            </div>

            <button type="submit" class="btn btn-primary">Guardar</button>
            <a asp-action="Listar" asp-controller="Mantenedor" class="btn btn-warning">Volver a la lista</a>
        </form>
    </div>
</div>

C#crudweb/Views/Mantenedor/GuardarLista.cshtml
@model ContactoModelo;
@{
    ViewData["Title"] = "GuardarLista";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Crear Contacto
    </div>
    <div class="card-body">
        <form asp-action="Guardar" asp-controller="Mantenedor" method="post">
            <div class="mb-3">
                <label for="nombre" class="form-label">Nombre:</label>
                <input asp-for="Nombre" type="text" class="form-control" id="nombre" aria-describedby="NameHelp">
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label for="telefono" class="form-label">Teléfono:</label>
                <input  asp-for="Telefono" type="text" class="form-control" id="telefono">
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>            
            <div class="mb-3">
                <label for="mail" class="form-label">Correo:</label>
                <input asp-for="Correo"  type="email" class="form-control" id="mail">
                <span asp-validation-for="Correo" class="text-danger"></span>
            </div>

            <button type="submit" class="btn btn-primary">Guardar</button>
            <a asp-action="Listar" asp-controller="Mantenedor" class="btn btn-warning">Volver a la lista</a>
        </form>
    </div>
</div>

C#crudweb/Views/Mantenedor/Listar.cshtml
@model List<ContactoModelo>
@{
    ViewData["Title"] = "Listar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Mostrar Contactos
    </div>
    <div class="card-body">


        <a asp-action="Guardar" asp-controller="Mantenedor" class="btn btn-success">Crear Nuevo</a>
        <hr />
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Telefono</th>
                    <th>Correo</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Nombre</td>
                        <td>@item.Telefono</td>
                        <td>@item.Correo</td>
                        <td><a asp-action="Editar" asp-controller="Mantenedor" asp-route-IdContacto="@item.IdContacto" class="btn btn-primary btn-sm">Editar</a></td>
                        <td><a asp-action="Eliminar" asp-controller="Mantenedor" asp-route-IdContacto="@item.IdContacto" class="btn btn-danger btn-sm">Eliminar</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

C#crudweb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - C_crudweb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/C_crudweb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">C_crudweb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - C_crudweb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>